-- MySQL Script generated by MySQL Workbench
-- Wed Jan 23 14:43:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_Igreja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_Igreja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_Igreja` DEFAULT CHARACTER SET utf8 ;
USE `DB_Igreja` ;

-- -----------------------------------------------------
-- Table `DB_Igreja`.`membros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Igreja`.`membros` (
  `idmembros` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nasc` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `supervisao` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idmembros`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
